### ISSUE TITLE
Create unity project and setup plugins etc.

### ISSUE THREAD

**Issue by Sarah-Lettmann** [felix-klose/papermate#1]

**Comment by felix-klose** [comment]
Created the project and imported UI Builder / UI Elements packages. So far no networking engine is installed since no networking package has been decided on.

**Comment by felix-klose** [comment]
Check out MLAPI ( https://docs-multiplayer.unity3d.com/docs/migration/install ) for networking

**Comment by felix-klose** [comment]
Added MLAPI package. Since this project is mainly UI and Networking, no further packages for core functionality should be necessary. 3rd-Party Assets may be installed later as necessary
